<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends AbstractRepositiory {

    public function search($term, $order = 'asc', $limit = 20, $offset = 0) {
        $qb = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.title', $order);
        if($term) {
            $qb
                ->where('a.title LIKE ?1')
                ->setParameter(1, '%' . $term . '%');
        }
        return $this->paginate($qb, $limit, $offset);
    }

}
